/**
 * ProjectAMPH Academy: Centralized Icon Registry
 *
 * Built on lucide-react — all icons are tree-shakeable named exports.
 * Single source of truth for all icon imports across the codebase.
 *
 * Usage:
 *   import { icons, Icon } from '@/components/icons';
 *
 *   // dynamic (e.g. badge system: icons[name] where name is a string)
 *   const IconComponent = icons['Trophy'];
 *
 *   // static JSX — import the specific icon you need
 *   import { Trophy } from '@/components/icons';
 *   <Trophy className="h-5 w-5" />
 *
 *   // generic wrapper for kebab-case names (backward compat)
 *   <Icon name="trophy" className="h-5 w-5" />
 */

import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  SquareArrowOutUpRight,
  RotateCw,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowUpDown,
  Check,
  X,
  Plus,
  Minus,
  Copy,
  Download,
  Printer,
  LogOut,
  Settings,
  CheckCircle,
  XCircle,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Ban,
  HelpCircle,
  Lock,
  Eye,
  EyeOff,
  Play,
  Pause,
  Video,
  Users,
  User,
  UserPlus,
  BarChart,
  TrendingUp,
  TrendingDown,
  Sliders,
  Target,
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Zap,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  Search,
  FolderOpen,
  FileText,
  CheckSquare,
  GraduationCap,
  Rocket,
  Coins,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Monitor,
  Calendar,
  Bell,
  Activity,
  Loader,
  Pen,
  Trash2,
  Share,
  Send,
  Menu,
  HeartPulse,
  MessageSquare,
  PieChart,
  RotateCcw,
  Layers,
  MousePointerClick,
  FlaskConical,
  UserCog,
  Building2,
  Mail,
  Bot,
  Grid3X3,
  DollarSign,
  Percent,
  MousePointer,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

// Map our kebab-case names (used in <Icon name="...">) to Lucide components
// Only icons that need custom mapping (kebab doesn't PascalCase cleanly, or name differs)
const KEBAB_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'square-arrow-out-up-right': SquareArrowOutUpRight,
  'rotate-cw': RotateCw,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-up-down': ArrowUpDown,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'triangle-alert': AlertCircle,
  'alert-octagon': AlertOctagon,
  'check': Check,
  'x': X,
  'plus': Plus,
  'minus': Minus,
  'pencil': Pen,
  'trash-2': Trash2,
  'copy': Copy,
  'share-2': Share,
  'download': Download,
  'printer': Printer,
  'send': Send,
  'log-out': LogOut,
  'menu': Menu,
  'settings': Settings,
  'lock': Lock,
  'eye': Eye,
  'eye-off': EyeOff,
  'play': Play,
  'pause': Pause,
  'video': Video,
  'users': Users,
  'user': User,
  'user-plus': UserPlus,
  'bar-chart': BarChart,
  'trend-up': TrendingUp,
  'trending-down': TrendingDown,
  'pulse': Activity,
  'spinner': Loader,
  'sliders': Sliders,
  'target': Target,
  'trophy': Trophy,
  'medal': Medal,
  'crown': Crown,
  'star': Star,
  'flame': Flame,
  'lightning': Zap,
  'book-open': BookOpen,
  'clock': Clock,
  'calculator': Calculator,
  'shield': Shield,
  'layout': LayoutTemplate,
  'layout-dashboard': LayoutDashboard,
  'lightbulb': Lightbulb,
  'sparkle': Sparkles,
  'sparkles': Sparkles,
  'funnel': Funnel,
  'magnifying-glass': Search,
  'folder-open': FolderOpen,
  'file-text': FileText,
  'check-square': CheckSquare,
  'graduation-cap': GraduationCap,
  'rocket': Rocket,
  'coins': Coins,
  'gauge': Gauge,
  'brain': Brain,
  'circle': Circle,
  'circle-dot': CircleDot,
  'info': Info,
  'database': Database,
  'server': Server,
  'globe': Globe,
  'desktop': Monitor,
  'calendar': Calendar,
  'bell': Bell,
  'warning': AlertTriangle,
  'ban': Ban,
  'help-circle': HelpCircle,
  'building-2': Building2,
  'mail': Mail,
  'bot': Bot,
  'grid-3x3': Grid3X3,
  'layers': Layers,
  'flask-conical': FlaskConical,
  'user-cog': UserCog,
  'mouse-pointer-click': MousePointerClick,
  'cursor': MousePointer,
};

export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  SquareArrowOutUpRight,
  RotateCw,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowUpDown,
  Check,
  X,
  Plus,
  Minus,
  Pen as Pencil,
  Trash2,
  Copy,
  Share,
  Download,
  Printer,
  Send,
  LogOut,
  Menu,
  Settings,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Ban,
  Loader,
  HelpCircle,
  Lock,
  Eye,
  EyeOff,
  Play,
  Pause,
  Video,
  Users,
  User,
  UserPlus,
  UserCog,
  Building2,
  Mail,
  Bot,
  BarChart,
  TrendingUp as TrendUp,
  TrendingDown,
  Sliders,
  Target,
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Zap,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  Search,
  FolderOpen,
  FileText,
  Grid3X3,
  CheckSquare,
  Layers,
  GraduationCap,
  FlaskConical,
  Rocket,
  Coins,
  MousePointerClick,
  HeartPulse,
  MessageSquare,
  PieChart,
  RotateCcw,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Monitor,
  Calendar,
  Bell,
  Activity,
  Pen,
  Trash2 as Trash2Icon,
  DollarSign,
  Percent,
  MousePointer,
  CheckCircle,
  XCircle,
};

/** Aliases for icons consumers expect but have different names in lucide-react */
export const Cursor = MousePointer;
export const MagnifyingGlass = Search;
export type { LucideIcon };

/** Alias for components that use AlertTriangle as TriangleAlert */
export const TriangleAlert = AlertTriangle;
export function Icon({ name, className, ...props }: { name: string; className?: string; [key: string]: unknown }) {
  const Component = KEBAB_MAP[name];
  if (!Component) return null;
  return <Component className={className} {...props} />;
}

/**
 * Icon registry — maps string names to Lucide icon components.
 * Use for dynamic icon rendering (e.g. database-driven badge icons).
 *
 * Example:
 *   const badgeIconName = 'Trophy'; // from database
 *   const IconComponent = icons[badgeIconName];
 *   {IconComponent && <IconComponent size={16} />}
 */
export const icons: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  // Navigation
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  SquareArrowOutUpRight,
  ArrowUpDown,
  RotateCw,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  // Actions
  Check,
  X,
  Plus,
  Minus,
  Pen,
  Trash2,
  Copy,
  Share,
  Download,
  Printer,
  Send,
  LogOut,
  Menu,
  Settings,
  // Status
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  AlertOctagon,
  Ban,
  Loader,
  Lock,
  Activity,
  // Media
  Play,
  Video,
  Pause,
  // Social
  Users,
  User,
  UserPlus,
  UserCog,
  Building2,
  Mail,
  Bot,
  // Data & Charts
  BarChart,
  TrendingUp,
  TrendingDown,
  Target,
  // Objects
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Zap,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  Search,
  FolderOpen,
  FileText,
  Grid3X3,
  CheckSquare,
  Layers,
  GraduationCap,
  FlaskConical,
  Rocket,
  Coins,
  MousePointerClick,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Eye,
  EyeOff,
  Monitor,
  Calendar,
  Bell,
  DollarSign,
  Percent,
  MousePointer,
};

/** All valid icon names */
export type IconName = keyof typeof icons;
