/**
 * ProjectAMPH Academy: Centralized Icon Registry
 *
 * Built on lucide-react — all icons are tree-shakeable named exports.
 * Single source of truth for all icon imports across the codebase.
 *
 * Usage:
 *   import { icons, Icon } from '@/components/icons';
 *
 *   // dynamic (e.g. badge system: icons[name] where name is a string)
 *   const IconComponent = icons['Trophy'];
 *
 *   // static JSX — import the specific icon you need
 *   import { Trophy } from '@/components/icons';
 *   <Trophy className="h-5 w-5" />
 *
 *   // generic wrapper for kebab-case names (backward compat)
 *   <Icon name="trophy" className="h-5 w-5" />
 */

import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowSquareOut,
  ArrowClockwise,
  CaretLeft,
  CaretRight,
  CaretDown,
  CaretUp,
  ArrowUpDown,
  Check,
  X,
  Plus,
  Minus,
  Copy,
  Download,
  Printer,
  LogOut,
  Settings,
  CheckCircle,
  XCircle,
  AlertCircle,
  Warning,
  Ban,
  HelpCircle,
  Lock,
  Eye,
  EyeOff,
  Play,
  Pause,
  Video,
  Users,
  User,
  UserPlus,
  BarChart,
  TrendUp,
  TrendingDown,
  Sliders,
  Target,
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Lightning,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  MagnifyingGlass,
  FolderOpen,
  FileText,
  CheckSquare,
  GraduationCap,
  Rocket,
  Coins,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Desktop,
  Calendar,
  Bell,
  Activity,
  Loader,
  Pen,
  Trash2,
  Share,
  Send,
  Menu,
  MousePointerClick,
  Layers,
  FlaskConical,
  UserCog,
  Building2,
  Mail,
  Bot,
  Grid3X3,
  XCircle,
} from 'lucide-react';

// Map our kebab-case names (used in <Icon name="...">) to Lucide components
// Only icons that need custom mapping (kebab doesn't PascalCase cleanly, or name differs)
const KEBAB_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
  'arrow-square-out': ArrowSquareOut,
  'arrow-clockwise': ArrowClockwise,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'caret-down': CaretDown,
  'caret-up': CaretUp,
  'arrow-up-down': ArrowUpDown,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'triangle-alert': AlertCircle,
  'check': Check,
  'x': X,
  'plus': Plus,
  'minus': Minus,
  'pencil': Pen,
  'trash-2': Trash2,
  'copy': Copy,
  'share-2': Share,
  'download': Download,
  'printer': Printer,
  'send': Send,
  'log-out': LogOut,
  'menu': Menu,
  'settings': Settings,
  'lock': Lock,
  'eye': Eye,
  'eye-off': EyeOff,
  'play': Play,
  'pause': Pause,
  'video': Video,
  'users': Users,
  'user': User,
  'user-plus': UserPlus,
  'bar-chart': BarChart,
  'trend-up': TrendUp,
  'trending-down': TrendingDown,
  'pulse': Activity,
  'spinner': Loader,
  'sliders': Sliders,
  'target': Target,
  'trophy': Trophy,
  'medal': Medal,
  'crown': Crown,
  'star': Star,
  'flame': Flame,
  'lightning': Lightning,
  'book-open': BookOpen,
  'clock': Clock,
  'calculator': Calculator,
  'shield': Shield,
  'layout': LayoutTemplate,
  'layout-dashboard': LayoutDashboard,
  'lightbulb': Lightbulb,
  'sparkle': Sparkles,
  'sparkles': Sparkles,
  'funnel': Funnel,
  'magnifying-glass': MagnifyingGlass,
  'folder-open': FolderOpen,
  'file-text': FileText,
  'check-square': CheckSquare,
  'graduation-cap': GraduationCap,
  'rocket': Rocket,
  'coins': Coins,
  'gauge': Gauge,
  'brain': Brain,
  'circle': Circle,
  'circle-dot': CircleDot,
  'info': Info,
  'database': Database,
  'server': Server,
  'globe': Globe,
  'desktop': Desktop,
  'calendar': Calendar,
  'bell': Bell,
  'warning': Warning,
  'ban': Ban,
  'help-circle': HelpCircle,
  'building-2': Building2,
  'mail': Mail,
  'bot': Bot,
  'grid-3x3': Grid3X3,
  'layers': Layers,
  'flask-conical': FlaskConical,
  'user-cog': UserCog,
  'mouse-pointer-click': MousePointerClick,
};

export {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowSquareOut,
  ArrowClockwise,
  CaretLeft,
  CaretRight,
  CaretDown,
  CaretUp,
  ArrowUpDown,
  Check,
  X,
  Plus,
  Minus,
  Pen as Pencil,
  Trash2,
  Copy,
  Share,
  Download,
  Printer,
  Send,
  LogOut,
  Menu,
  Settings,
  CheckCircle,
  XCircle,
  AlertCircle,
  Warning,
  Ban,
  Loader,
  HelpCircle,
  Lock,
  Eye,
  EyeOff,
  Play,
  Video,
  Pause,
  Users,
  User,
  UserPlus,
  UserCog,
  Building2,
  Mail,
  Bot,
  BarChart,
  TrendUp,
  TrendingDown,
  Sliders,
  Target,
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Lightning,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  MagnifyingGlass,
  FolderOpen,
  FileText,
  Grid3X3,
  CheckSquare,
  Layers,
  GraduationCap,
  FlaskConical,
  Rocket,
  Coins,
  MousePointerClick,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Desktop,
  Calendar,
  Bell,
  Activity,
  Pen,
  Trash2 as Trash2Icon,
};

/** Generic Icon wrapper — accepts kebab-case name strings for dynamic rendering */
export function Icon({ name, className, ...props }: { name: string; className?: string; [key: string]: unknown }) {
  const Component = KEBAB_MAP[name];
  if (!Component) return null;
  return <Component className={className} {...props} />;
}

/**
 * Icon registry — maps string names to Lucide icon components.
 * Use for dynamic icon rendering (e.g. database-driven badge icons).
 *
 * Example:
 *   const badgeIconName = 'Trophy'; // from database
 *   const IconComponent = icons[badgeIconName];
 *   {IconComponent && <IconComponent size={16} />}
 */
export const icons: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  // Navigation
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowSquareOut,
  ArrowUpDown,
  ArrowClockwise,
  CaretLeft,
  CaretRight,
  CaretDown,
  CaretUp,
  // Actions
  Check,
  X,
  Plus,
  Minus,
  Pen,
  Trash2,
  Copy,
  Share,
  Download,
  Printer,
  Send,
  LogOut,
  Menu,
  Settings,
  // Status
  CheckCircle,
  XCircle,
  Warning,
  AlertCircle,
  Ban,
  Loader,
  HelpCircle,
  Lock,
  Activity,
  // Media
  Play,
  Video,
  Pause,
  // Social
  Users,
  User,
  UserPlus,
  UserCog,
  Building2,
  Mail,
  Bot,
  // Data & Charts
  BarChart,
  TrendUp,
  TrendingDown,
  Sliders,
  Target,
  // Objects
  Trophy,
  Medal,
  Crown,
  Star,
  Flame,
  Lightning,
  BookOpen,
  Clock,
  Calculator,
  Shield,
  Layout,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  Sparkles,
  Funnel,
  MagnifyingGlass,
  FolderOpen,
  FileText,
  Grid3X3,
  CheckSquare,
  Layers,
  GraduationCap,
  FlaskConical,
  Rocket,
  Coins,
  MousePointerClick,
  Gauge,
  Brain,
  Circle,
  CircleDot,
  Info,
  Database,
  Server,
  Globe,
  Eye,
  EyeOff,
  Desktop,
  Calendar,
  Bell,
};

/** All valid icon names */
export type IconName = keyof typeof icons;
